title: Arch Melange
description: Speciális Arch Linux disztribúciók KDE Plasma környezettel.
baseurl: "/arch-melange" # Ha a repó neve nem felhasznalonev.github.io, akkor hagyd ezt itt.
url: "https://felhasznalonev.github.io" # Cseréld le a sajátodra
theme: null
